import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import SearchBar from "../components/Home/searchbar/SearchBar";
import Banner from "../components/Home/Banner/Banner";
import Stories from "../components/Home/Stories/Stories";
import News from "../components/Home/News/News";
import AllArticles from "../components/Home/Articles/AllArticles";
import TradingFAQ from "../components/Home/FAQ/TradingFAQ";
import SliderImage from "../components/Home/Slider/Slider";
import Sliders from "../components/Home/Slider/TestSlider";
import Dummy from "../components/Dummy/Dummy";

export default function Home() {
  return (
    <>
      <Head>
        <title>Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* other script.js can be run here */}
      </Head>
      <Script></Script>
      <SearchBar></SearchBar>
      <SliderImage></SliderImage>
      {/* <Sliders></Sliders> */}
      <Banner></Banner>
      <Stories></Stories>
      <News></News>
      <AllArticles></AllArticles>
      <TradingFAQ></TradingFAQ>
      {/* <nav className={styles.nav_style}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/blog">
            <li>Blogs</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
        </ul>
      </nav> */}
      {/* <main className={styles.main}>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  );
}
